99 signup
GSG-G11/herfa pull request #100
Opened 2022-05-12 16:56 UTC by devstm

2022-05-12 18:53 UTC, RandSohail approved these changes

2022-05-12 20:52 UTC, LinaYahya requested changes
Great Job والله 🥳

2022-05-12 20:52 UTC, LinaYahya commented on server/utils/validation/signUpValidation.js
> +  image: Joi.string().required(),
I guess we will not send an image in the signup route

2022-05-12 20:52 UTC, LinaYahya commented on server/utils/validation/signUpValidation.js
> +  mainServiceId: Joi.number().required(),
and sub-services which is not required

2022-05-12 20:52 UTC, LinaYahya commented on server/controllers/signup/index.js
> +      next(customError(err.message, 400));
either to return or to add else block for next error

2022-05-12 20:52 UTC, LinaYahya commented on server/controllers/signup/dataToInsert.js
> +  const whatsappNumber = whatsapp.slice(2);
leave a comment about the shape of WhatsApp number

2022-05-12 20:52 UTC, LinaYahya commented on server/controllers/signup/index.js
> +    const user = await User.create(dataToInsert);
find a way to insert subservices

2022-05-14 08:44 UTC, LinaYahya approved these changes

2022-05-14 13:31 UTC, abdulrahman-2020 approved these changes

2022-05-14 13:31 UTC, merged