Edit Component
GSG-G11/herfa pull request #101
Opened 2022-05-13 18:17 UTC by RandSohail

- Open modal that allows the user to 
- Edit the title of the work 
- Edit the content
- Edit the image

2022-05-14 15:48 UTC, abdulrahman-2020 approved these changes

2022-05-14 15:48 UTC, AbdallahGot approved these changes

2022-05-14 19:18 UTC, devstm approved these changes

2022-05-14 19:18 UTC, devstm commented on client/src/Components/AddWorkButton/index.tsx
> +  const checkImage = (file: any) => {
try to user accept props to Upload Component to allow to user upload specific files type 
in ant design: 
![image](https://user-images.githubusercontent.com/54906217/168445337-fc8c037c-97cb-461b-acc7-b5a019285570.png)

and if you jump to See [input accept Attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#accept)

`<input type="file" id="docpicker"
  accept=".doc,.docx,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document">`

2022-05-14 19:18 UTC, devstm commented on client/src/Components/AddWorkButton/index.tsx
> +        .then(async (values) => {
then and await? 
what is this?

2022-05-14 19:18 UTC, devstm commented on server/controllers/errors/server.js
> +  console.log(err);
remove the console hhhhhhhhhhhhhhhhhhaaaaaa

2022-05-14 19:19 UTC, devstm requested changes

2022-05-14 19:19 UTC, devstm commented on server/utils/s3.js
>  }
nothing

2022-05-15 08:24 UTC, abdulrahman-2020 approved these changes

2022-05-15 08:42 UTC, devstm approved these changes

2022-05-15 10:17 UTC, LinaYahya approved these changes

2022-05-15 10:17 UTC, merged