feat: create image Profile Upload controller
GSG-G11/herfa pull request #107
Opened 2022-05-15 11:56 UTC by abdulrahman-2020

Relates #106

2022-05-17 12:49 UTC, LinaYahya approved these changes

2022-05-17 12:51 UTC, LinaYahya requested changes
Good Job AbedRahman,
Just delete the empty style file

2022-05-17 12:51 UTC, LinaYahya commented on client/src/Components/ProfileImageUpload/index.tsx
> +  setImage:(image:string)=>void,
```suggestion
  setImage:()=>void,
```

2022-05-17 12:53 UTC, RandSohail approved these changes

2022-05-18 06:01 UTC, LinaYahya approved these changes

2022-05-18 08:04 UTC, LinaYahya approved these changes

2022-05-18 08:04 UTC, devstm approved these changes

2022-05-18 08:07 UTC, merged