Style Pages
GSG-G11/herfa pull request #109
Opened 2022-05-15 19:37 UTC by RandSohail

- Style log in page

2022-05-16 15:47 UTC, abdulrahman-2020 approved these changes

2022-05-16 18:48 UTC, LinaYahya requested changes

2022-05-16 20:20 UTC, RandSohail commented on client/src/Components/UserCard/index.tsx
> +            {/* <p>{whatsapp}</p> */}
in the search page I think it's not important to put all the craftsman info he can see in the search the most important data like name, phone number and his location. If the user interest  he can enter the profile

2022-05-17 07:13 UTC, AbdallahGot approved these changes

2022-05-17 07:14 UTC, devstm approved these changes

2022-05-17 07:15 UTC, LinaYahya approved these changes

2022-05-17 07:15 UTC, merged