94 signup form2
GSG-G11/herfa pull request #110
Opened 2022-05-16 08:23 UTC by AbdallahGot

2022-05-16 19:01 UTC, LinaYahya reviewed
things to do
- setUser after signup
- remove route to layout route

2022-05-17 09:08 UTC, devstm approved these changes

2022-05-17 09:19 UTC, RandSohail approved these changes

2022-05-17 09:22 UTC, LinaYahya requested changes

2022-05-17 09:22 UTC, LinaYahya commented on server/controllers/signup/checkPhone.js
> +    console.log(phone);
```suggestion
```

2022-05-17 09:22 UTC, LinaYahya commented on client/src/App.tsx
> +                <Route path="/signup" element={<SignUp />} />
```suggestion
```

2022-05-17 09:38 UTC, LinaYahya approved these changes

2022-05-17 09:38 UTC, merged