check translation
GSG-G11/herfa pull request #118
Opened 2022-05-17 15:32 UTC by AbdallahGot

add translation for location, services and subServices.

2022-05-19 08:30 UTC, devstm approved these changes

2022-05-19 09:11 UTC, abdulrahman-2020 approved these changes

2022-05-19 11:03 UTC, LinaYahya requested changes
Also, change Ar at nav to العربية
and try to change the document title in the `app.tsx` use effect based on language

2022-05-20 09:35 UTC, LinaYahya approved these changes

2022-05-20 09:35 UTC, merged