add review model to create a review table
GSG-G11/herfa pull request #21
Opened 2022-04-20 20:04 UTC by AbdallahGot

relates #17

2022-04-20 20:30 UTC, devstm approved these changes

2022-04-20 23:13 UTC, RandSohail approved these changes

2022-04-21 06:17 UTC, LinaYahya requested changes

2022-04-21 06:17 UTC, LinaYahya commented on server/database/models/review.js
> +    allowNull: false,
this should be a reference to userID

2022-04-21 08:01 UTC, LinaYahya approved these changes

2022-04-21 08:03 UTC, abdulrahman-2020 approved these changes

2022-04-21 08:13 UTC, merged