Get /home Route
GSG-G11/herfa pull request #31
Opened 2022-04-22 19:57 UTC by RandSohail

- Bring locations data
- Bring top 10 reviews 
- Bring main services

2022-04-23 07:42 UTC, abdulrahman-2020 approved these changes

2022-04-23 08:58 UTC, devstm commented on server/controllers/home/index.js
> +    response.json({ location: locationFromDB, topTenReviews: reviewFromDB, services: mainServices });
response must be json opject with msg and data!
const data = { location: locationFromDB, topTenReviews: reviewFromDB, services: mainServices }
response.json({ msg: "home page data" , data});

2022-04-23 09:54 UTC, devstm approved these changes

2022-04-23 10:18 UTC, LinaYahya requested changes

2022-04-23 10:18 UTC, LinaYahya commented on server/controllers/home/index.js
> +    // eslint-disable-next-line max-len
Don't disable just wrap your line

2022-04-23 10:18 UTC, LinaYahya commented on server/controllers/home/index.js
> +    const reviewFromDB = await Review.findAll({
here we're waiting for locations to get mainServivces after that we get top ten reviews, 
this id take a time while we're don't need to wait for location to get services as it don't depend on
So maybe we can use 
`Promise.all([])` OR `Promise.all Settled([])`

Read more about the difference [Promise all](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all)

2022-04-23 10:18 UTC, LinaYahya commented on server/routes/index.js
> +router.get('/home', Home);
```suggestion
});

router.get('/home', getHomeData);
```

2022-04-23 10:18 UTC, LinaYahya commented on server/test/homeRoute.test.js
> +
I suppose that you run build for test_url,
But this is locally
So we need here to run the build function 
```js
beforeAll(() => build)
```
and after all we need to close connection

2022-04-24 06:53 UTC, LinaYahya requested changes

2022-04-24 06:53 UTC, LinaYahya commented on server/controllers/home/index.js
> +      topTenReviews: await Review.findAll({
promise.all built to receive an array of promises, What you're doing here you give it one element as an object that will wait for promises to finish

2022-04-24 06:53 UTC, LinaYahya commented on server/routes/index.js
> +router.get('/home', getHomeData);
I would prefer if our endpoint was `/` instead of `/home`

2022-04-24 08:36 UTC, AbdallahGot approved these changes

2022-04-24 08:39 UTC, LinaYahya approved these changes

2022-04-24 08:39 UTC, merged