feat: create GET /providers/:id to response user profile information
GSG-G11/herfa pull request #33
Opened 2022-04-22 22:28 UTC by devstm

Relates #29

create controller function to get all user information 
end point: /providers/:id
data responded:
![localhost_3030_api_v1_providers_2](https://user-images.githubusercontent.com/54906217/164803666-bba46474-702a-4c94-8b1f-80c7933feeea.png)
9

2022-04-23 06:55 UTC, abdulrahman-2020 approved these changes

2022-04-23 07:17 UTC, RandSohail approved these changes

2022-04-23 07:54 UTC, AbdallahGot approved these changes

2022-04-23 09:59 UTC, LinaYahya requested changes

2022-04-23 09:59 UTC, LinaYahya commented on server/controllers/user/profile.js
> +    const reviews = await Review.findAll({
Do we need to get all review we only need to get the top five or ten reviews,
The same for works I think in the first fetch we need to get the most recent four or six works as we have in figma, then when user navigate to the next page we can fetch more

And as we're not getting the whole reviewsm we still need the whole rate for that provider

2022-04-23 09:59 UTC, LinaYahya commented on server/controllers/user/profile.js
> +    const locations = await user.getLocation();
can you imagine how many await we have here,
Why not trying to fetch data using include to join tables we have
```js
await User.findByPk(id, {
      include: [{ model: Location }, { model: SubServices }],
      })
 ```
 So what if user here will be null ?! Do we need to send status 200, I doubt that
 So we need to check if user exists then maybe we can get reviews and works after that
 and while neither review nor work depends on each other we can run queries at the same time using `Promise.all`
 
 And did you notice that we're sending passwords to the client-side!! 😨 
 Also, it's good to not sending all raws even we don't use, So try to exclude columns we don't need

2022-04-23 09:59 UTC, LinaYahya commented on server/test/testData.js
> +const testData = {
we don't need to test routes on fake data,
we need to build fake data first as we did before
so afterAll tests run build 
and after all test close connection

2022-04-23 09:59 UTC, LinaYahya commented on server/utils/validation/params.js
> +// this file to validate params.id attribute
rename file name 
validation/params not explain anythings

2022-04-24 10:41 UTC, LinaYahya reviewed
Good job Saleh, just add a total rate for that provider
and works page count

2022-04-24 10:41 UTC, LinaYahya commented on server/controllers/user/profile.js
> +      await Review.findAll({
```suggestion
       Review.findAll({
```

2022-04-24 10:41 UTC, LinaYahya commented on server/routes/index.js
> +router.get('/providers/:id', profile);
```suggestion
router.get('/providers/:id', getProviderInfo);
```

2022-04-24 10:41 UTC, LinaYahya commented on server/test/profile.test.js
> +  });
remove that test and add a test to test not found user

2022-04-24 12:55 UTC, LinaYahya requested changes

2022-04-24 12:55 UTC, LinaYahya commented on server/controllers/user/profile.js
> +    console.log(fn);
remove that line

2022-04-24 12:55 UTC, LinaYahya commented on server/controllers/user/profile.js
> +    const count = await Review.count({ where: { userId: id } }); // 50
use promise all

2022-04-24 13:15 UTC, merged