create UserInfoCard component
GSG-G11/herfa pull request #34
Opened 2022-04-23 07:40 UTC by abdulrahman-2020

- create a card using antd

- add icons using fontawesome-react library

2022-04-23 10:27 UTC, LinaYahya requested changes

2022-04-23 10:27 UTC, LinaYahya commented on client/src/components/profile/UserInfoCard.tsx
> +function UserInfoCard() {
build your component to receive props,
and In the place you call add these data as props

2022-04-23 10:27 UTC, LinaYahya commented on client/src/components/profile/UserInfoCard.tsx
> +        <FontAwesomeIcon icon={faStarHalf} size="lg" />
check rate component at antd

2022-04-23 10:27 UTC, LinaYahya commented on client/src/components/profile/UserInfoCard.tsx
> +          أضف تقيماً
translate any text you have

2022-04-23 10:27 UTC, LinaYahya commented on client/src/Pages/Profile.tsx
> +      <UserInfoCard />
```suggestion
      <UserInfoCard userInfo={{image, name, ...etc}} />
```

2022-04-24 11:26 UTC, AbdallahGot approved these changes

2022-04-24 12:03 UTC, RandSohail approved these changes

2022-04-24 12:15 UTC, LinaYahya requested changes

2022-04-24 12:15 UTC, LinaYahya commented on client/src/components/UserInfoCard/UserInfoCard.tsx
> +import React from 'react';
rename file to index.tsx

2022-04-24 12:15 UTC, LinaYahya commented on client/src/components/UserInfoCard/UserInfoCard.tsx
> +import '../../App.css';
No need to import stylesheet here as you import it at app.tsx

2022-04-24 12:15 UTC, LinaYahya commented on client/src/components/UserInfoCard/UserInfoCard.tsx
> +import 'antd/dist/antd.css';
remove this line as you already import it in the App.tsx

2022-04-24 12:15 UTC, LinaYahya commented on client/src/components/UserInfoCard/UserInfoCard.tsx
> +          {useTranslation().t('servicesOffer')}
invoke useTranslation out of return

2022-04-24 12:15 UTC, LinaYahya commented on client/src/components/UserInfoCard/UserInfoCard.tsx
> +            <Link to={instagram}><FontAwesomeIcon style={{ color: '#AA38A5' }} icon={faInstagram} size="2x" /></Link>
while we're navigating outside our route use an anchor tag instead.

2022-04-24 12:15 UTC, LinaYahya commented on client/src/components/UserInfoCard/UserInfoCard.tsx
> +// };
remove comments

2022-04-24 12:15 UTC, LinaYahya commented on client/src/components/UserInfoCard/UserInfoCard.tsx
> +interface IUserInfoCardProps {
```suggestion
interface UserInfoCardProps {
```

2022-04-24 12:15 UTC, LinaYahya commented on client/src/components/UserInfoCard/UserInfoCard.tsx
> +import './userInfocard.css';
rename your file to style.css

2022-04-24 12:15 UTC, LinaYahya commented on client/package.json
> +    "babel-plugin-macros": "^3.1.0",
why you install it?

2022-04-24 12:58 UTC, LinaYahya approved these changes

2022-04-24 13:00 UTC, devstm approved these changes

2022-04-24 13:01 UTC, merged