feat: crate work component
GSG-G11/herfa pull request #39
Opened 2022-04-24 11:12 UTC by devstm

2022-04-25 12:15 UTC, LinaYahya requested changes

2022-04-25 12:15 UTC, LinaYahya commented on client/src/Components/UserInfoCard/index.tsx
> +      first_name, last_name, services, image, phone, email, description, location,
```suggestion
      first_name: firstName, last_name: lastName, services, image, phone, email, description, location,
```

2022-04-25 12:15 UTC, LinaYahya commented on client/src/Components/UserInfoCard/index.tsx
> +      // eslint-disable-next-line camelcase
```suggestion
```
remove eslint rules disable

2022-04-25 12:15 UTC, LinaYahya commented on client/src/Components/UserInfoCard/index.tsx
> +            {/* eslint-disable-next-line camelcase */}
```suggestion
```

2022-04-25 12:15 UTC, LinaYahya commented on client/src/Components/UserInfoCard/index.tsx
> +            {services && services.map((service: any) => (
```suggestion
            {services && services.map((service: string) => (
```

2022-04-25 12:15 UTC, LinaYahya commented on client/src/Pages/Profile.tsx
> +// eslint-disable-next-line import/extensions
```suggestion
```
fix eslint errors

2022-04-25 12:15 UTC, LinaYahya commented on client/src/Pages/Profile.tsx
> +        setError(error1?.data.msg);
we need to setLoading to false even if error happened

2022-04-25 12:15 UTC, LinaYahya commented on client/src/Pages/Profile.tsx
> +      } catch (error1: any) {
```suggestion
      } catch (err: Error) {
```

2022-04-25 12:15 UTC, LinaYahya commented on client/src/Pages/Profile.tsx
> +        setData(data);
no need to set works to data

2022-04-25 12:15 UTC, LinaYahya commented on client/src/utils/types/profile.ts
> +export type User = {
How Great!

2022-04-25 14:30 UTC, LinaYahya requested changes

2022-04-25 14:30 UTC, LinaYahya commented on client/src/Pages/Profile.tsx
> +        setWorks(allWorks1);
```suggestion
        setWorks({
          1: [...works],
        });
```

2022-04-25 14:30 UTC, LinaYahya commented on client/src/Pages/Profile.tsx
> +              <WorkCard work={work} actions={act} isAuth={isAuth} />
key is missing here

2022-04-26 07:45 UTC, RandSohail approved these changes

2022-04-26 07:46 UTC, devstm commented
create work card component in profile page

2022-04-26 07:48 UTC, LinaYahya approved these changes

2022-04-26 07:48 UTC, merged