create main services component
GSG-G11/herfa pull request #40
Opened 2022-04-24 11:21 UTC by RandSohail

2022-04-24 13:33 UTC, devstm approved these changes

2022-04-24 13:34 UTC, LinaYahya requested changes

2022-04-24 13:34 UTC, LinaYahya commented on client/src/Components/mainServices/MainServicesCard.tsx
> +import './mainServices.css';
rename file to style.css

2022-04-24 13:34 UTC, LinaYahya commented on client/src/Components/mainServices/MainServicesCard.tsx
> +import 'antd/dist/antd.css';
```suggestion
```
No need to import as we import antd style at App.tsx

2022-04-24 13:34 UTC, LinaYahya commented on client/src/Components/mainServices/MainServicesCard.tsx
> +      <img src={`../../../images/${imgLink + 1}.png`} alt="main service we provide" className="main-services-crd-image" />
```suggestion
      <img src={`/images/${imgLink + 1}.png`} alt="main service we provide" className="main-services-crd-image" />
```
anything inside public simply have a path of /etc
and we can change alt to service text

2022-04-24 13:34 UTC, LinaYahya commented on client/src/Components/mainServices/index.tsx
> +/* eslint-disable max-len */
fix eslint rules

2022-04-25 06:30 UTC, LinaYahya approved these changes

2022-04-25 07:14 UTC, abdulrahman-2020 approved these changes

2022-04-25 07:15 UTC, merged