feat: create pagination controller
GSG-G11/herfa pull request #44
Opened 2022-04-25 14:38 UTC by abdulrahman-2020

- create pagination controller

Relates #41

2022-04-25 15:08 UTC, LinaYahya requested changes
Good Job AbedRahman,
Small changes required and add tests also

2022-04-25 15:08 UTC, LinaYahya commented on server/utils/validation/workIdValidation.js
> +  id: Joi.number().integer().positive().required(),
```suggestion
  id: Joi.number().integer().positive().required(),
  page: // create a page validation though 
```

2022-04-25 15:08 UTC, LinaYahya commented on server/controllers/pagenation/index.js
> +    const pageData = await Work.findAndCountAll({
Why you're using count here!

2022-04-26 22:30 UTC, devstm requested changes

2022-04-26 22:30 UTC, devstm commented on server/controllers/pagenation/index.js
> +    console.log(pageData);
remove console.log

2022-04-26 22:30 UTC, devstm commented on server/controllers/pagenation/index.js
> +    if (!pageData.count) {
If there is no works; response status code should be 400 and message  "There Is No Works".
I think 'Page Not Found' not descriptive message

2022-04-27 08:00 UTC, RandSohail approved these changes

2022-04-27 08:49 UTC, devstm approved these changes

2022-04-27 08:50 UTC, LinaYahya approved these changes

2022-04-27 08:50 UTC, merged