57 search for provider
GSG-G11/herfa pull request #62
Opened 2022-04-28 14:01 UTC by devstm

search for provider by name or location 
![image](https://user-images.githubusercontent.com/54906217/165768894-3ac8983c-b228-439e-acca-066a232c1c40.png)

2022-04-29 21:53 UTC, abdulrahman-2020 approved these changes

2022-05-05 12:42 UTC, RandSohail approved these changes

2022-05-05 13:28 UTC, AbdallahGot approved these changes

2022-05-05 13:43 UTC, LinaYahya commented on server/controllers/user/search.js
> +    }));
```suggestion

```

2022-05-07 07:24 UTC, LinaYahya requested changes

2022-05-07 07:24 UTC, LinaYahya commented on server/controllers/user/search.js
> +      where,
```suggestion
      where,
      attributes: {
        exclude: ['password', 'createdAt', 'updatedAt'],
      },
```

2022-05-07 07:24 UTC, LinaYahya commented on server/controllers/user/search.js
> +        { model: Location },
Select attribuates you need only for all models
```suggestion
        { model: Location,  attributes: ['city'] },
```

2022-05-07 07:24 UTC, LinaYahya commented on server/utils/validation/searchRequestValidation.js
> +  subservice: Joi.string(),
```suggestion
  subservice: Joi.array().items(Joi.number())
```

2022-05-07 07:24 UTC, LinaYahya commented on server/controllers/user/search.js
> +    } = await searchRequestValidation.validateAsync(req.query);
try to validate subservice after split it, So if 
```js
if(req.query.subservice){
// split
}
// then validate
await searchRequestValidation.validateAsync({...req.query, subservice: splittedArr})
```

2022-05-07 08:57 UTC, LinaYahya approved these changes

2022-05-07 09:00 UTC, merged