feat: add checkauthorization middleware
GSG-G11/herfa pull request #65
Opened 2022-04-29 12:08 UTC by AbdallahGot

2022-04-29 13:39 UTC, LinaYahya requested changes

2022-04-29 13:39 UTC, LinaYahya commented on server/utils/checkAuth.js
> +        req.providerID = providerID;
use async await instead

2022-04-29 13:39 UTC, LinaYahya commented on server/utils/checkAuth.js
> +const verifyToken = require('./jwt/verifyToken');
export from utils index,
And remove this file to `middleware.js` file inside controller

2022-04-29 14:46 UTC, RandSohail approved these changes

2022-04-30 01:10 UTC, abdulrahman-2020 approved these changes

2022-05-05 08:11 UTC, devstm approved these changes

2022-05-05 09:49 UTC, LinaYahya approved these changes

2022-05-05 09:49 UTC, merged