add login controller
GSG-G11/herfa pull request #69
Opened 2022-05-02 01:02 UTC by AbdallahGot

1. email and password validation.
2. check if the email exists or not.
3. if the email exists check if the password is correct or not.

2022-05-05 11:32 UTC, LinaYahya requested changes

2022-05-05 11:32 UTC, LinaYahya commented on server/database/models/getDataUsingEmail.js
> +const getEmail = (userEmail) => User.findOne({ where: { email: userEmail } });
all we're doing here is to call findOne from user, so there is no need to create  a separate function for it, 
In the place you want to find a user call your method there

2022-05-05 11:32 UTC, LinaYahya commented on server/controllers/login/index.js
> +    const checkedEmail = await getEmail(validateValue.email);
```suggestion
    const {id, password: hashedPassword} = await User.findOne({ where: { email: validateValue.email } });
```

2022-05-05 11:32 UTC, LinaYahya commented on server/controllers/login/index.js
> +    const validateValue = await loginValidation(req.body);
destructure email and password from there
```suggestion
    const {email, password} = await loginValidation(req.body);
```

2022-05-05 11:32 UTC, LinaYahya commented on server/utils/signToken.js
> +module.exports = (userId) => new Promise((resolve, reject) => {
You can put it in the  `jwt` file

2022-05-05 11:32 UTC, LinaYahya commented on server/controllers/login/index.js
> +    if (err.name === 'ValidationError') next(customError(err.message, 401));
```suggestion
    if (err.name === 'ValidationError') next(customError(err.message, 400));
```

2022-05-05 11:32 UTC, LinaYahya commented on server/controllers/login/index.js
> +    if (signTokenCookie) res.cookie('userToken', signTokenCookie);
there's always a signToken, So need to check if exist or not,

2022-05-05 11:32 UTC, LinaYahya commented on server/controllers/login/index.js
> +    res.json({ msg: 'logged in successfully ..', data: { id: checkedEmail.id } });
also send user name here, which is a firstName + ' ' + lastName

2022-05-07 18:24 UTC, LinaYahya approved these changes

2022-05-07 18:27 UTC, LinaYahya requested changes

2022-05-07 18:27 UTC, LinaYahya commented on server/controllers/login/index.js
> +    const { email: userEmail, password: hashedPassword } = await loginValidation(req.body);
```suggestion
    const { email: userEmail, password } = await loginValidation(req.body);
```

2022-05-07 18:27 UTC, LinaYahya commented on server/controllers/login/index.js
> +      id, password, first_name, last_name,
```suggestion
      id, password: hashedPassword, first_name, last_name,
```

2022-05-07 18:27 UTC, LinaYahya commented on server/controllers/login/index.js
> +    const checkedPassword = await compare(hashedPassword, password);
```suggestion
    const checkedPassword = await compare(password, hashedPassword);
```

2022-05-07 18:27 UTC, LinaYahya commented on server/utils/jwt.js
> +  sign({ providerName, providerID: userId, role: 'provider' }, process.env.SECRET_KEY, (err, token) => {
```suggestion
  sign({ providerName, providerID: userId}, process.env.SECRET_KEY, (err, token) => {
```
No more need for the role here

2022-05-07 18:41 UTC, RandSohail approved these changes

2022-05-07 18:50 UTC, devstm approved these changes

2022-05-08 05:07 UTC, abdulrahman-2020 approved these changes

2022-05-08 07:47 UTC, LinaYahya approved these changes

2022-05-08 07:47 UTC, merged