create delete work route and testing it
GSG-G11/herfa pull request #73
Opened 2022-05-05 11:05 UTC by abdulrahman-2020

Relates #71

- create delete work controller
- testing delete from database

2022-05-05 12:05 UTC, LinaYahya requested changes

2022-05-05 12:05 UTC, LinaYahya commented on server/routes/index.js
> +router.get('/providers/:id', checkAuth, getProfileInfo);
```suggestion
router.get('/providers/:id', getProfileInfo);
```

2022-05-05 12:05 UTC, LinaYahya commented on server/test/profile.test.js
> +      .set('Cookie', [`token= ${process.env.token}`])
```suggestion
```
Remove this line for all GET /providers/:id tests

2022-05-05 12:05 UTC, LinaYahya commented on server/controllers/work/deleteWork.js
> +    await work.destroy({ where: { id } });
you need to check first if the user who send the request the same how own the work

2022-05-05 13:39 UTC, LinaYahya requested changes

2022-05-05 13:39 UTC, LinaYahya commented on server/controllers/work/deleteWork.js
> +    const { userId } = req.body;
actually work has a userID as `userId`,
So we'll get userid from it not from request body

2022-05-05 13:39 UTC, LinaYahya commented on server/test/work.test.js
> +  test('Testing for delete work /api/v1/work/1 and get status 401', (done) => {
add a test to test when user want to chack a work how doesn't own

2022-05-07 18:35 UTC, LinaYahya approved these changes

2022-05-07 18:40 UTC, RandSohail approved these changes

2022-05-07 18:54 UTC, devstm approved these changes

2022-05-07 21:59 UTC, AbdallahGot approved these changes

2022-05-08 05:00 UTC, merged