filter search page
GSG-G11/herfa pull request #74
Opened 2022-05-05 16:16 UTC by RandSohail

- filter search
- Search by name just input
- Search by main services depend on its search by sub-services
- Search by location 
![Capture](https://user-images.githubusercontent.com/32583123/166967625-6e9566ed-021b-479d-9800-0411a5bf9831.PNG)

2022-05-07 08:26 UTC, LinaYahya requested changes

2022-05-07 08:26 UTC, LinaYahya commented on client/src/Components/FilterSection/index.tsx
> +        onSelect={(service: number) => handelSelectMainService(service)}
input handler shouldn't send a request,
The best thing to do is to set input handler setState for the main service then in useEffect, you can send a request to get sub services based on the main service user select

2022-05-07 08:26 UTC, LinaYahya commented on client/src/Components/FilterSection/index.tsx
> +        disabled={selectMainService}
try to control the input yourself, So add a value and onChange to it,
So in the main service selection when user select a new main service you can clear or set the sub services value to empty array

2022-05-07 08:26 UTC, LinaYahya commented on client/src/Components/FilterSection/index.tsx
> +      <Select placeholder={t('city')} className="filter-inputs">
try to add default values based on location state
```suggestion
      <Select placeholder={t('city')} className="filter-inputs" defaultValue={search?.locationSearch}>
```
the same for other inputs might hold a state

2022-05-07 18:55 UTC, devstm approved these changes

2022-05-08 08:28 UTC, AbdallahGot approved these changes

2022-05-08 08:34 UTC, LinaYahya approved these changes

2022-05-08 08:34 UTC, merged