77 update work
GSG-G11/herfa pull request #78
Opened 2022-05-07 16:36 UTC by abdulrahman-2020

2022-05-08 06:48 UTC, devstm requested changes

2022-05-08 06:48 UTC, devstm commented on server/controllers/work/editWork.js
> +    console.log(req.body);
remove console.log()

2022-05-08 18:42 UTC, RandSohail approved these changes

2022-05-09 13:40 UTC, devstm commented on server/routes/index.js
> +  getProfileInfo, addReview, getSearchResult, getHomeData, getWorkPerPage, subServices, checkAuth,
fix ESlent

2022-05-10 08:57 UTC, LinaYahya requested changes

2022-05-10 08:57 UTC, LinaYahya commented on server/routes/index.js
> +router.patch('/work/editWork/', checkAuth, editWork);
```suggestion
router.patch('/work/', checkAuth, editWork);
```

2022-05-10 08:57 UTC, LinaYahya commented on server/database/seeders/works.js
> +    image: 'dfghjkl;',
add a valid link

2022-05-10 08:57 UTC, LinaYahya commented on server/controllers/work/editWork.js
> +    const { title, content } = req.body;
```suggestion
    const { id, title, content  } = await workEditValidation.validateAsync(req.body);
```

2022-05-10 08:57 UTC, LinaYahya commented on server/controllers/work/editWork.js
> +      image: imgUrl.Location,
if not req.files, then imgUrl will be an empty string, and `imgUrl.Location` will throw an error,
And you need to set the image value if it's not send with req.files from the request body

2022-05-10 08:57 UTC, LinaYahya commented on server/controllers/work/editWork.js
> +      deleteImage(work.image);
move this after sending the response, at the end of the controller so we don't delay user from getting a response

2022-05-10 08:57 UTC, LinaYahya commented on server/controllers/work/editWork.js
> +      deleteImage(work.image);
Also the delete image take the key, which is part of the url, But not the whole url
So when the url is 
`https://herfa.s3.eu-west-2.amazonaws.com/2/f7454dc0-cf6a-11ec-a5f1-61119f11f019.png`
the key woukd be 
`2/f7454dc0-cf6a-11ec-a5f1-61119f11f019.png`
So try to split after `url.com`

2022-05-10 08:57 UTC, LinaYahya commented on server/test/work.test.js
> +  //     .expect(401)
add tests to test unauthorized user, and work not found

2022-05-10 12:33 UTC, LinaYahya requested changes

2022-05-10 12:33 UTC, LinaYahya commented on server/controllers/work/editWork.js
> +    if (work.userId !== +providerID) {
```suggestion
    const { userId, image, id } = work;
     if (work.userId !== +providerID) {
```
Work really updated after update, so we have to save the image value we want to get the key from, On this place

2022-05-10 14:03 UTC, LinaYahya approved these changes

2022-05-10 14:06 UTC, devstm requested changes

2022-05-10 14:06 UTC, devstm commented on server/controllers/work/editWork.js
> +    const work = await Work.findByPk(id);
why we do that this is additional request to data base which we can avoid it 
so we can read { userId, image } from request body then check 
but how can handle work doesn't exist?
to know: sequelize update method retern array has 0 if failed and one if success after ubdata we can check if zero then response user with un auth message

2022-05-10 14:08 UTC, devstm approved these changes

2022-05-10 14:10 UTC, merged