82 search page
GSG-G11/herfa pull request #83
Opened 2022-05-08 21:02 UTC by devstm

2022-05-09 08:13 UTC, RandSohail approved these changes

2022-05-09 09:26 UTC, LinaYahya requested changes
Also add clear to your inputs, 
So If I can clear location If I want

2022-05-09 09:26 UTC, LinaYahya commented on client/src/Components/FilterSection/index.tsx
> +      queryString += `&page=${page}`;
No need to this condition
Just in the end before sending the request add 
```suggestion
      queryString += `&page=${page}`;
```

2022-05-09 09:26 UTC, LinaYahya commented on client/src/Components/FilterSection/index.tsx
> +      setUsers(searchResult.data);
What if we declare the function outside the component and pass to it a success and failure callback
```js
  const getSearchResults = async (queryString: string, successCB, faluireCB) => {};
  ```

2022-05-09 19:22 UTC, abdulrahman-2020 approved these changes

2022-05-10 05:39 UTC, LinaYahya approved these changes

2022-05-10 05:40 UTC, merged