feat: add login form component and the function after submit to handl…
GSG-G11/herfa pull request #87
Opened 2022-05-09 13:06 UTC by AbdallahGot

…e the login process

2022-05-10 13:07 UTC, LinaYahya requested changes

2022-05-11 06:18 UTC, LinaYahya requested changes

2022-05-11 06:18 UTC, LinaYahya commented on client/src/Components/Login/LoginFrom.tsx
> +      console.log(location);
remove these two lines,
Actually, we want to redirect user  after success so no need to display a message for user

2022-05-11 06:18 UTC, LinaYahya commented on client/src/Components/Login/LoginFrom.tsx
> +      console.log(location);
```suggestion
      
```

2022-05-11 06:18 UTC, LinaYahya commented on client/src/Components/Login/LoginFrom.tsx
> +      }, 1000);
No need,
Just after `axios`,  loginResult set it to false

2022-05-11 06:18 UTC, LinaYahya commented on client/src/Components/Login/LoginFrom.tsx
> +      if (err.response) {
```suggestion
             setLoading(false);
      if (err.response) {
```

2022-05-11 13:05 UTC, LinaYahya approved these changes

2022-05-11 13:09 UTC, RandSohail approved these changes

2022-05-11 13:14 UTC, abdulrahman-2020 approved these changes

2022-05-11 13:36 UTC, merged