Profile Page
GSG-G11/herfa pull request #95
Opened 2022-05-11 07:02 UTC by devstm

sooon .....

2022-05-11 17:08 UTC, RandSohail commented on client/src/Components/WorksList/index.tsx
> +import WorkCard from '../WorkCard/WorkCard';
rename workCard.tsx to index.tsx 
and call him directly 
```
import WorkCard from '../WorkCard';
```

2022-05-11 17:11 UTC, RandSohail commented on client/src/Components/WorksList/index.tsx
> +import WorkCard from '../WorkCard/WorkCard';
it was fixed in main branch just pull it

2022-05-11 17:12 UTC, RandSohail commented on client/src/Components/WorksList/index.tsx
> +              <WorkCard key={work?.id} work={work} actions={act} isAuth={isAuth} />
workCard does not need an actions props anymore just pull the main

2022-05-11 17:15 UTC, RandSohail commented on client/src/Pages/Profile.tsx
> +import getWorksData from '../Controllers/getWorks';
make an index file in the controller's folder and import getWorksData, getProfileData from it directly

2022-05-12 20:42 UTC, LinaYahya requested changes
Good Job Saleh, appreciated effort 👏🏼 
additional small notes to fix,
Just make sure to remove the work when delete is success,
And It's a good to redirect user to not found user or render a customized component for `not found user`, In case of a validation error, when sending a request for `user/aaa` or when user not found as `user/1000`
And keep a comment for rand to add `add Work` button in the provider card

2022-05-12 20:42 UTC, LinaYahya commented on client/src/Controllers/getProfileData.ts
> +    const { count } = data;
```suggestion
interface ProviderDataType {
user: User,
works: Works,
reviews: ,
}
const {user, works, reviews, totalReviews, count}: ProviderDataType = data
```

2022-05-12 20:42 UTC, LinaYahya commented on client/src/Controllers/getProfileData.ts
> +    setIsLoading(false);
```suggestion
    setIsLoading(false);
```
Remove this line immediately when the response come back

2022-05-12 20:42 UTC, LinaYahya commented on client/src/Pages/Profile.tsx
> +    setWorksData(works);
Let us assume that we are in the first page, Storing thw work data for the first page in the state, And now I want to go to the third page,
SO we're setting the whole state with the new works, And now I want to go to the first page again, So I should send the request again while I had the data before,
This doesn't make any sense
I think the best way to do that is to store the new works beside the one we have related to the page contain,

I think this the best way to store the state
```js
const [works, setWorks] = useState({1: worksForPage1, 3: worksForPage3})
```

And then In the use effect, I should check if I have `works[page]`, then no need to send the request

2022-05-12 20:42 UTC, LinaYahya commented on server/controllers/user/profile.js
> +    console.log(error);
```suggestion
```
Add a console.log in the `serverError` controller

2022-05-15 18:32 UTC, LinaYahya requested changes
Great Job Saleh,
small things to fix
1- add `form.resetFields();` to `handleAddWork` at `workModal` component
2- don't display `review` and `contact` buttons, when `isAuth`
3- try to handle add review, to render the new review in the slider
4- replace `cover` image at `workCard/index` to use Antd image, to get used of preview feature, and change alt to work title

2022-05-15 18:32 UTC, LinaYahya commented on client/src/Components/WorksList/index.tsx
> +          <Empty description={(<span>no-data</span>)} />
```suggestion
          <Empty description={(<span>{t('no-data')}</span>)} />
```

2022-05-16 08:11 UTC, LinaYahya approved these changes

2022-05-16 08:29 UTC, AbdallahGot approved these changes

2022-05-16 08:32 UTC, merged