feat: create signup step1 commponent
GSG-G11/herfa pull request #96
Opened 2022-05-11 15:43 UTC by abdulrahman-2020

Relates #91
create signup step 1 component
check email exsist and send message from back

2022-05-12 17:19 UTC, devstm requested changes

2022-05-12 17:19 UTC, devstm commented on client/src/Pages/SignUp.tsx
> +import PersonalForm from '../Components/PersonalInformaion';
export PersonalInformaion to Component/index.tsx then import it from there

2022-05-12 17:19 UTC, devstm commented on client/src/Pages/SignUp.tsx
> +      {useTranslation().t('crate-account')}
destruct  t from useTranslation() becaouse we use more than once

2022-05-12 17:19 UTC, devstm commented on client/src/localization/local/ar.js
> +  Email: 'البريد الالكتروني',
abdullah use 
  'login-email': 'البريد الالكتروني',
so we can use it instead of write another

2022-05-15 07:32 UTC, AbdallahGot approved these changes

2022-05-15 07:49 UTC, LinaYahya requested changes

2022-05-15 07:49 UTC, LinaYahya commented on server/controllers/signUp/index.js
> +    res.json({ msg: 'Sign up successful', status: 200 });
```suggestion
    res.json({ msg: 'email valid, status: 200 });
```

2022-05-15 07:49 UTC, LinaYahya commented on client/src/Components/PersonalInformaion/index.tsx
> +            onChange={handleChange}
```suggestion
```

2022-05-15 07:49 UTC, LinaYahya commented on client/src/Components/PersonalInformaion/index.tsx
> +      const { data } = await axios.post('/api/v1/signUp', userInfo);
change endpoint to `/checkemail`
and only send email

2022-05-15 08:24 UTC, LinaYahya approved these changes

2022-05-15 08:43 UTC, devstm approved these changes

2022-05-15 08:45 UTC, RandSohail approved these changes

2022-05-15 08:45 UTC, merged